### ISSUE TITLE
Dogecoin Code 1.14.8 has been released

### ISSUE THREAD

**Issue by GaryLittlemore** [shermand100/pinode-doge#11]
PiNode-Doge is still running on 1.14.7, 1.14.8 was released on the 2nd August. Will PiNode-Doge be getting an update to the latest release?

**Comment by shermand100** [comment]
Master Branch Dogecoin v1.14.8 tag and file paths updated - commit https://github.com/shermand100/pinode-doge/commit/47c7f89eca084cf7f9cb620fd2657d424ec26943

Armbian-Debian Branch relevant files - commit https://github.com/shermand100/pinode-doge/commit/394c8deb74a121570c1e4292ccc83e18621333f3

Raspberry Pi OS relevant files - commit https://github.com/shermand100/pinode-doge/commit/32a7e648501c933ddce7b2c9c898734cec92c4f7


Anyway, although I've updated version numbers and links are you able to test the update for me and report back? Should be as smooth as the other updates but I don't have a device spare at the moment for testing.

**Comment by GaryLittlemore** [comment]
Hi, sorry for the delay in getting back to you. I've performed the update, it looks like it's been successful.

![image](https://github.com/user-attachments/assets/2852b622-98c1-499b-a16c-5d11ad4ccd22)

![image](https://github.com/user-attachments/assets/5c435d25-e67f-49ae-89ad-1b40ae67ed9e)
