### ISSUE TITLE
Ðogecoin 1.14.9 Core released.

### ISSUE THREAD

**Issue by GaryLittlemore** [shermand100/pinode-doge#12]
https://github.com/dogecoin/dogecoin/releases/tag/v1.14.9

**Comment by shermand100** [comment]
Thanks for the heads-up.

For all our supported hardware PiNodeDOGE has been updated accordingly on branches
Main:
https://github.com/shermand100/pinode-doge/tree/842a7bae0b2cb41ae3aeba36cb9e4c770cff8707
Armbian:
https://github.com/shermand100/pinode-doge/commit/6274717888b5d8994a0368c13ac78060f9e94c5c
Raspberry Pi OS:
https://github.com/shermand100/pinode-doge/commit/5b24e6633122237e9498485fb0223c23bd7aa48d


Please let me know if you encounter any issues with the update.

Thanks,
Dan

**Comment by GaryLittlemore** [comment]
All upgraded and appears to be running without any issues. TY. ![image](https://github.com/user-attachments/assets/a15aafd3-ae59-444f-981e-93abb13f46b4)

**Comment by shermand100** [comment]
Good stuff.

Closing for now. If you encounter issues regarding the update feel free to reopen.
